version: '3.7'
services:
  keycloak:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm.json
      - DB_DATABASE=qa-portal
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - type: bind
        source: ./qa-portal-infra/keycloak/qa-portal-realm.json
        target: /tmp/realm.json
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qa-portal
  portal-core:
    image: amoghvnaik/portal-core:latest
    build: ./qa-portal-angular
    depends_on:
      - keycloak
      - core-api
      - user-api
      - self-reflection-api
      - course-api
      - cv-api
      - feedback-api
      - question-api
    ports:
      - target: 80
        published: 80

