version: '3.7'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - portal-core
      - database
      - keycloak
      - feedback-api
      - self-reflection-api
      - form-api
      - cohort-api
      - portal-application-api
      
  keycloak:
    image: jboss/keycloak:6.0.1
    depends_on:
      - database
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_DATABASE=qa-portal
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PROXY_ADDRESS_FORWARDING=true
    command: -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/opt/jboss/exported_realms -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    volumes:
    - type: bind
      source: ./qa-portal-infra/keycloak/exported_realms
      target: /opt/jboss/exported_realms

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  portal-core:
    image: thebartthe/portal-core:build-${BUILD_NUMBER}
    build: ./qa-portal-angular
    depends_on:
      - keycloak
  cv-api:
    image: thebartthe/cv-api:build-${BUILD_NUMBER}
    build:
      context: ./qa-portal-services
      args: 
        - PROJECT=cv-api
  form-api:
    image: thebartthe/form-api:build-${BUILD_NUMBER}
    build:
      context: ./qa-portal-services
      args: 
        - PROJECT=form-api
  self-reflection-api:
    image: thebartthe/self-reflection-api:build-${BUILD_NUMBER}
    build:
      context: ./qa-portal-services
      args: 
        - PROJECT=self-reflection-api
  feedback-api:
    image: thebartthe/feedback-api:build-${BUILD_NUMBER}
    build:
      context: ./qa-portal-services
      args: 
        - PROJECT=feedback-api
  cohort-api:
    image: thebartthe/cohort-api:build-${BUILD_NUMBER}
    build:
      context: ./qa-portal-services
      args: 
        - PROJECT=cohort-api
  portal-application-api:
    image: thebartthe/portal-application-api:build-${BUILD_NUMBER}
    build:
      context: ./qa-portal-services
      args: 
        - PROJECT=portal-application-api
