version: '3.7'
services:
  keycloak:
    image: deployment:5000/keycloak:build-${BUILD_NUMBER}
    build: ./qa-portal-infra
  portal-core:
    image: deployment:5000/portal-core:build-${BUILD_NUMBER}
    build: ./qa-portal-angular
  cv-api:
    image: deployment:5000/cv-api:build-${BUILD_NUMBER}
    build:
      context: ./qa-portal-services
      args: 
        - PROJECT=cv-api
  form-api:
    image: deployment:5000/form-api:build-${BUILD_NUMBER}
    build:
      context: ./qa-portal-services
      args: 
        - PROJECT=form-api
  self-reflection-api:
    image: deployment:5000/self-reflection-api:build-${BUILD_NUMBER}
    build:
      context: ./qa-portal-services
      args: 
        - PROJECT=self-reflection-api
  feedback-api:
    image: deployment:5000/feedback-api:build-${BUILD_NUMBER}
    build:
      context: ./qa-portal-services
      args: 
        - PROJECT=feedback-api
  cohort-api:
    image: deployment:5000/cohort-api:build-${BUILD_NUMBER}
    build:
      context: ./qa-portal-services
      args: 
        - PROJECT=cohort-api
  portal-application-api:
    image: deployment:5000/portal-application-api:build-${BUILD_NUMBER}
    build:
      context: ./qa-portal-services
      args: 
        - PROJECT=portal-application-api
