version: "3.7"

services:
  frontend:
    image: vieran:latest
    build: ./qa-portal-angular
    depends_on:
      - keycloak
    ports:
      - target: 80
        published: 80
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  keycloak:
    image: keycloak
    container_name: keycloak
    build: ./qa-portal-infra
    depends_on:
      - database
    ports:
      - 8070:8080
  
  feedback-api:
    image: feedback-1:latest
    build: ./qa-portal-services/feedback-api
    ports:
      - 8084:8084
  
  self-reflection-api:
    image: self-reflection
    build: ./qa-portal-services/self-reflection-api
    ports: 
      - 8082:8082
