version: "3.7"

services:
  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
      - database
      - keycloak

  frontend:
    image: hafizpatwary/angular-frontend:build-${BUILD_NUMBER}
    build: ./qa-portal-angular
    depends_on:
      - keycloak
    ports:
      - target: 80
        published: 5000
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


  keycloak:
    image: jboss/keycloak:6.0.1
    depends_on:
      - database
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_DATABASE=qa-portal
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PROXY_ADDRESS_FORWARDING=true
    command: -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/opt/jboss/exported_realms -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    volumes:
    - type: bind
      source: ./qa-portal-infra/keycloak/exported_realms
      target: /opt/jboss/exported_realms

