version: "3.7"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
      - database
      - keycloak
      - feedback-api
      - self-reflection-api
      - form-api
      - cohort-api
      - portal-application-api

  frontend:
    image: vieran:latest
    build: ./qa-portal-angular
    depends_on:
      - keycloak
    ports:
      - target: 80
        published: 5000
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  keycloak:
    image: keycloak
    container_name: keycloak
    build: ./qa-portal-infra
    depends_on:
      - database
    ports:
      - 8080:8080
  
  feedback-api:
    image: feedback-1:latest
    build: ./qa-portal-services/feedback-api
    ports:
      - 8084:8084
  
  self-reflection-api:
    image: self-reflection
    build: ./qa-portal-services/self-reflection-api
    ports: 
      - 8082:8082

  cohort-api:
    image: cohort
    build: ./qa-portal-services/cohort-api
    ports:
      - 8086:8086

  form-api:
    image: form
    build: ./qa-portal-services/form-api
    ports:
      - 8085:8085
  
  portal-application-api:
    image: portal-application
    build: ./qa-portal-services/portal-application-api
    ports:
      - 8081:8081

