apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: 
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: deployment:5000/portal-core:build-{{BUILD}}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-api
  labels: 
    app: cv-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-api
  template:
    metadata:
      labels:
        app: cv-api
    spec:
      containers:
      - name: cv-api
        image: deployment:5000/cv-api:build-{{BUILD}}
        ports:
        - containerPort: 8087

---
apiVersion: v1
kind: Service
metadata:
  name: cv-api
spec:
  selector:
    app: cv-api
  ports: 
  - protocol: TCP
    port: 8087
    targetPort: 8087
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-api
  labels: 
    app: cv-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-api
  template:
    metadata:
      labels:
        app: cv-api
    spec:
      containers:
      - name: cv-api
        image: deployment:5000/cv-api:build-{{BUILD}}
        ports:
        - containerPort: 8087

---
apiVersion: v1
kind: Service
metadata:
  name: cv-api
spec:
  selector:
    app: cv-api
  ports: 
  - protocol: TCP
    port: 8087
    targetPort: 8087
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels: 
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgresql
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports: 
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels: 
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports: 
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
