apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-core
  labels: 
    app: portal-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-core
  template:
    metadata:
      labels:
        app: portal-core
    spec:
      containers:
      - name: portal-core
        image: deployment:5000/portal-core:build-{{BUILD}}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portal-core
spec:
  selector:
    app: portal-core
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-api
  labels: 
    app: cv-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-api
  template:
    metadata:
      labels:
        app: cv-api
    spec:
      containers:
      - name: cv-api
        image: deployment:5000/cv-api:build-{{BUILD}}
        ports:
        - containerPort: 8087

---
apiVersion: v1
kind: Service
metadata:
  name: cv-api
spec:
  selector:
    app: cv-api
  ports: 
  - protocol: TCP
    port: 8087
    targetPort: 8087
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-api
  labels: 
    app: feedback-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-api
  template:
    metadata:
      labels:
        app: feedback-api
    spec:
      containers:
      - name: feedback-api
        image: deployment:5000/feedback-api:build-{{BUILD}}
        ports:
        - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: feedback-api
spec:
  selector:
    app: feedback-api
  ports: 
  - protocol: TCP
    port: 8084
    targetPort: 8084
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-api
  labels: 
    app: form-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form-api
  template:
    metadata:
      labels:
        app: form-api
    spec:
      containers:
      - name: form-api
        image: deployment:5000/form-api:build-{{BUILD}}
        ports:
        - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: form-api
spec:
  selector:
    app: form-api
  ports: 
  - protocol: TCP
    port: 8085
    targetPort: 8085
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-application-api
  labels: 
    app: portal-application-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-application-api
  template:
    metadata:
      labels:
        app: portal-application-api
    spec:
      containers:
      - name: portal-application-api
        image: deployment:5000/portal-application-api:build-{{BUILD}}
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: portal-application-api
spec:
  selector:
    app: portal-application-api
  ports: 
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-reflection-api
  labels: 
    app: self-reflection-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: self-reflection-api
  template:
    metadata:
      labels:
        app: self-reflection-api
    spec:
      containers:
      - name: self-reflection-api
        image: deployment:5000/self-reflection-api:build-{{BUILD}}
        ports:
        - containerPort: 8082 

---
apiVersion: v1
kind: Service
metadata:
  name: self-reflection-api
spec:
  selector:
    app: self-reflection-api
  ports: 
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cohort-api
  labels: 
    app: cohort-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cohort-api
  template:
    metadata:
      labels:
        app: cohort-api
    spec:
      containers:
      - name: cohort-api
        image: deployment:5000/cohort-api:build-{{BUILD}}
        ports:
        - containerPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: cohort-api
spec:
  selector:
    app: cohort-api
  ports: 
  - protocol: TCP
    port: 8086
    targetPort: 8086
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels: 
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgresql
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports: 
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels: 
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports: 
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
